apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    {{- include "trading.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "trading.selectorLabels" . | nindent 4 }}
