apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    {{- include "trading.labels" . | nindent 4 }}
    {{- include "trading.minio.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      {{- include "trading.minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.minio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trading.labels" . | nindent 8 }}
        {{- include "trading.minio.selectorLabels" . | nindent 8 }}
        {{- with .Values.minio.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.minio.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args:
            - server
            - /data
          ports:
            - name: tcp
              containerPort: {{ .Values.minio.port }}
              protocol: TCP
          {{- with .Values.minio.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.minio.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.minio.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
