apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    {{- include "trading.labels" . | nindent 4 }}
    {{- include "trading.minio.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: {{ .Values.minio.port }}
      protocol: TCP
      name: tcp
  selector:
    {{- include "trading.minio.selectorLabels" . | nindent 4 }}
